-- Create Tables for BarControl (Supabase/PostgreSQL)

-- 1. Bars
CREATE TABLE public.bars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Products (Insumos)
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    volume_total_ml NUMERIC NOT NULL, -- Volume in ml (e.g., 1000 for 1L)
    custo_garrafa NUMERIC NOT NULL, -- Cost per bottle
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Recipes (Drinks)
CREATE TABLE public.recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_drink TEXT NOT NULL,
    preco_venda NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Recipe Ingredients (Join Table)
CREATE TABLE public.recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
    quantidade_ml NUMERIC NOT NULL, -- Amount used in the recipe
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Inventory Sessions (Shifts)
CREATE TABLE public.inventory_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bar_id BIGINT REFERENCES public.bars(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id), -- Links to Supabase Auth
    data_inicio TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    data_fim TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Bottle Logs (Check-in/Check-out)
CREATE TABLE public.bottle_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT REFERENCES public.inventory_sessions(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE RESTRICT NOT NULL,
    numero_garrafa_canetao TEXT NOT NULL, -- Physical ID on the bottle
    
    -- Start of Session
    foto_url_inicio TEXT,
    nivel_inicio NUMERIC CHECK (nivel_inicio >= 0 AND nivel_inicio <= 100), -- 0 to 100
    
    -- End of Session
    foto_url_fim TEXT,
    nivel_fim NUMERIC CHECK (nivel_fim >= 0 AND nivel_fim <= 100), -- 0 to 100
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for performance
CREATE INDEX idx_recipe_ingredients_recipe ON public.recipe_ingredients(recipe_id);
CREATE INDEX idx_inventory_sessions_bar ON public.inventory_sessions(bar_id);
CREATE INDEX idx_bottle_logs_session ON public.bottle_logs(session_id);
CREATE INDEX idx_bottle_logs_product ON public.bottle_logs(product_id);

-- RLS Policies (Optional - Basic Setup)
ALTER TABLE public.bars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bottle_logs ENABLE ROW LEVEL SECURITY;

-- Allow read access to everyone (for now) or authenticated users
CREATE POLICY "Enable read access for all users" ON public.bars FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON public.products FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON public.recipes FOR SELECT USING (true);
